name: CI - ASP.NET API

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore demo_api.sln

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Build solution
        run: dotnet build demo_api.sln --configuration Release --no-restore

      - name: Verify EF Core Migrations
        working-directory: src/project.API
        run: dotnet ef migrations list

      - name: Run tests
        working-directory: src/project.API.Tests
        run: dotnet test --configuration Release --no-build
